require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'